### ISSUE TITLE
SAM nodes using old texture

### ISSUE THREAD

**Issue by budak7273** [budak7273/SatisfactoryBuildableResourceNodes#2]
https://discord.com/channels/555424930502541343/555505343031934979/1298351862491254866

**Comment by Th3Fanbus** [comment]
https://ficsit.app/mod/Th3SMBuilder to the rescue! Mesh is `SM_SAM_Node_01` and it uses the default mesh material (one slot, see picture)

![image](https://github.com/user-attachments/assets/16f96e68-2339-49f8-b899-c341e43477a0)

Size comparison:

![image](https://github.com/user-attachments/assets/d6cb9e6d-dbed-4ca5-8cb2-e795efa113dd)

**Comment by budak7273** [comment]
Fixed in 2.4.1
