### ISSUE TITLE
SAM node: mesh position is wrong

### ISSUE THREAD

**Issue by Th3Fanbus** [budak7273/SatisfactoryBuildableResourceNodes#3]
The SAM node mesh is not properly centered. It should have no horizontal offset and a vertical offset of about 50 cm so that it is not sunken into the ground.

![image](https://github.com/user-attachments/assets/59f90064-9925-49b1-bcbd-dbf0186a6a3a)

![image](https://github.com/user-attachments/assets/699e4909-e7a9-4807-81b8-5387da19828a)

**Comment by budak7273** [comment]
Seems like most of the old ore node meshes still needed these offsets to align correctly but the new SAM mesh does not.

**Comment by budak7273** [comment]
50cm made it protrude out of the ground a bit too much so I went with 35cm. It should look fine on foundations and flatish ground now

![image](https://github.com/user-attachments/assets/99f33131-95f0-4d86-a857-5b81f3aab0ea)


![image](https://github.com/user-attachments/assets/c006b39b-0c85-4c9c-b3c8-9cacaacec1c5)

**Comment by budak7273** [comment]
Fixed in 2.4.2

**Comment by Th3Fanbus** [comment]
Looks good, thank you! I remember using 50 cm in ExampleMod, but I just recalled I also scaled up the mesh by a factor of 1.35 or so.

If I ever get annoyed by grass clipping through these nodes, I'll consider making a buildable piece of ground (probably using the CliffCone mesh) with all the ground types there are (shouldn't be too bad, CliffCone already has MIs).
